name: CI

on:
  push:
  release:
    types: [ published ]

jobs:
  checks:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Set up Pre-commit
        uses: pre-commit/action@v2.0.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install .

      - uses: 'google-github-actions/setup-gcloud@v0'
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Run tests
        run: |
          pytest

  release:
    name: "Release to PyPI"
    runs-on: ubuntu-latest
    needs: checks
    if: "github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v')"
    steps:

      - uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: "Build package"
        run: |
          python setup.py build sdist

      - name: "TEST Upload to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event.release.prerelease
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: "Upload to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        if: "!github.event.release.prerelease"
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  build_push:
    name: Package docker image
    runs-on: ubuntu-18.04
    needs: ["checks", "release"]
    if: "success('checks') && !failure('release')"
    steps:
      #- uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build release image ----
      - name: "Release: Build and push"
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'release' &&  startsWith(github.event.release.tag_name, 'hub') }}
        with:
          push: true
          tags: ghcr.io/${{github.repository}}:${{ github.event.release.tag_name }}

      # build any image pushed on a branch starting with development ----
      - name: "Development: Build and push"
        uses: docker/build-push-action@v2
        if: ${{ github.event_name != 'release' && startsWith(github.ref_name, 'development') }}
        with:
          push: true
          tags: ghcr.io/${{github.repository}}:${{github.ref_name}}
