name: Build docker image

on:
  push:
    branches:
      - "*docker*"
  release:
    types: [ published ]

jobs:
  build_push:
    name: Package docker image
    runs-on: ubuntu-18.04
    steps:
      #- uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        with:
          push: true
          tags: ghcr.io/${{github.repository}}:${{ github.event.release.tag_name }}

      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ github.event_name != 'release' }}
        with:
          push: false
          tags: ghcr.io/${{github.repository}}:test
